FROM oven/bun:1

ARG DB_URL

WORKDIR /usr/src/app

COPY ../apps/web/package.json ./apps/web/package.json
COPY ../bun.lockb ../bun.lockb
COPY ../package.json ../package.json
COPY ../package-lock.json ../package-lock.json

RUN bun install

COPY . .

RUN bun run generate:db
RUN DB_URL=$DB_URL bunx turbo build --filter=web...

EXPOSE 3000

# Start the frontend application
CMD ["bun", "start:frontend"]